import { EntityWithRelations } from './service';

export interface RenderOptions {
  siteUrl?: string;
  basePath?: string;
}

export function renderEntityPage(
  entity: EntityWithRelations,
  options: RenderOptions = {}
): string {
  const { siteUrl = 'https://example.com', basePath = '' } = options;

  const schemaType = getSchemaType(entity.type);
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': schemaType,
    name: entity.name,
    description: entity.description || undefined,
    ...(entity.thumbnailUrl && { image: entity.thumbnailUrl }),
    ...(entity.attributes && mapAttributesToSchema(entity.type, entity.attributes)),
  };

  const attributesHtml = renderAttributesTable(entity.attributes);
  const relationsHtml = renderRelationsList(entity.relations, basePath);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(entity.name)} - Entity Page</title>
  <meta name="description" content="${escapeHtml(entity.description || `${entity.name} - ${entity.type}`)}">
  <link rel="canonical" href="${siteUrl}/entity/${entity.slug}">
  <script type="application/ld+json">${JSON.stringify(jsonLd)}</script>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; }
    .container { max-width: 900px; margin: 0 auto; padding: 2rem; }
    .card { background: white; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); padding: 2rem; margin-bottom: 1.5rem; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; color: #111; }
    .entity-type { display: inline-block; padding: 0.25rem 0.75rem; background: #e0e7ff; color: #3730a3; border-radius: 9999px; font-size: 0.875rem; font-weight: 500; margin-bottom: 1rem; }
    .description { color: #666; margin-bottom: 1.5rem; }
    h2 { font-size: 1.25rem; margin-bottom: 1rem; color: #111; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }
    table { width: 100%; border-collapse: collapse; }
    th, td { text-align: left; padding: 0.75rem; border-bottom: 1px solid #e5e7eb; }
    th { background: #f9fafb; font-weight: 600; width: 30%; }
    .relations-list { list-style: none; }
    .relations-list li { padding: 0.5rem 0; border-bottom: 1px solid #f3f4f6; }
    .relations-list li:last-child { border-bottom: none; }
    .relations-list a { color: #4f46e5; text-decoration: none; }
    .relations-list a:hover { text-decoration: underline; }
    .predicate { color: #6b7280; font-size: 0.875rem; }
    .empty-state { color: #9ca3af; font-style: italic; }
    footer { text-align: center; padding: 2rem; color: #9ca3af; font-size: 0.875rem; }
  </style>
</head>
<body>
  <div class="container">
    <div class="card">
      <span class="entity-type">${escapeHtml(entity.type)}</span>
      <h1>${escapeHtml(entity.name)}</h1>
      ${entity.description ? `<p class="description">${escapeHtml(entity.description)}</p>` : ''}

      <h2>Attributes</h2>
      ${attributesHtml}
    </div>

    <div class="card">
      <h2>Related Entities</h2>
      ${relationsHtml}
    </div>
  </div>

  <footer>
    <p>Generated by AI SEO CMS Entity Service</p>
  </footer>
</body>
</html>`;
}

function getSchemaType(entityType: string): string {
  const typeMap: Record<string, string> = {
    product: 'Product',
    brand: 'Brand',
    technology: 'Technology',
    person: 'Person',
    concept: 'Thing',
  };
  return typeMap[entityType] || 'Thing';
}

function mapAttributesToSchema(type: string, attrs: Record<string, string>): Record<string, unknown> {
  const mapped: Record<string, unknown> = {};

  if (type === 'product') {
    if (attrs.price) mapped.offers = { '@type': 'Offer', price: attrs.price, priceCurrency: 'USD' };
    if (attrs.rating) mapped.aggregateRating = { '@type': 'AggregateRating', ratingValue: attrs.rating };
  }

  return mapped;
}

function renderAttributesTable(attributes: Record<string, string>): string {
  const entries = Object.entries(attributes);

  if (entries.length === 0) {
    return '<p class="empty-state">No attributes available.</p>';
  }

  const rows = entries.map(([key, value]) => {
    const formattedKey = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    return `<tr><th>${escapeHtml(formattedKey)}</th><td>${escapeHtml(value)}</td></tr>`;
  }).join('');

  return `<table><tbody>${rows}</tbody></table>`;
}

function renderRelationsList(relations: Array<{ predicate: string; objectEntity?: { slug: string; name: string } }>, basePath: string): string {
  if (relations.length === 0) {
    return '<p class="empty-state">No related entities.</p>';
  }

  const items = relations.map(rel => {
    const name = rel.objectEntity?.name || 'Unknown';
    const slug = rel.objectEntity?.slug || '#';
    const href = `${basePath}/entity/${slug}`;
    return `<li><a href="${escapeHtml(href)}">${escapeHtml(name)}</a> <span class="predicate">(${escapeHtml(rel.predicate)})</span></li>`;
  }).join('');

  return `<ul class="relations-list">${items}</ul>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}